controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Infrastructure/Http/Controller/
        namespace: App\Infrastructure\Http\Controller
    type: attribute

# JWT Login
api_login:
    path: /api/login
    methods: ['POST']
